server:
  host: localhost
  port: 9100
  grpc:
    host: localhost
    port: 9000

security:
  salt: 330a8b08c3b4c61533e1d0c5ce1ac88f
  checksum:
    algorithms:
      - sha-1
      - sha-256
      - sha-384
      - sha-512

meeting:
  camera:
    cap: 0
    max_pinned: 3
  features:
    disabled:
  duration: 0
  expiry:
    no_user_joined_in_min: 5
    last_user_left_in_min: 1

user:
  camera:
    cap: 3
  inactivity:
    inspect_interval: 0
    threshold: 30

recording:
  notify_recording_is_on: false

presentation:
  upload:
    external:
      description:
      url:

breakout_rooms:
  record: false
  private_chat_enabled: true
