presentation:
  uploadEndpoint: '/bigbluebutton/presentation/upload'
  uploadSizeMin: 0
  uploadSizeMax: 50000000
  uploadValidMimeTypes:
    - 'application/vnd.ms-excel'
    - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    - 'application/msword'
    - 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    - 'application/vnd.ms-powerpoint'
    - 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    - 'application/vnd.oasis.opendocument.text'
    - 'application/rtf'
    - 'text/plain'
    - 'application/vnd.oasis.opendocument.spreadsheet'
    - 'application/vnd.oasis.opendocument.presentation'
    - 'application/pdf'
    - 'image/jpeg'
    - 'image/png'
