#   Shortcut Configurations
shortcuts:
  # 
  toggle_fullsreen:
    keys: 'Control+Alt+0'
    descId: 'shortcut001'
  toggle_userlist:
    keys: 'Control+Alt+1'
    descId: 'shortcut002'
  mute_unmute:
    keys: 'Control+Alt+M'
    descId: 'shortcut003'
  logout:
    keys: 'Control+Alt+L'
    descId: 'shortcut004'
  open_about: 
    keys: 'Control+Alt+8'
    descId: 'shortcut005'
  open_settings: 
    keys: 'Control+Alt+9'
    descId: 'shortcut006'
  previous_slide: 
    keys: 'Control+Alt+A'
    descId: 'shortcut007'
  next_slide: 
    keys: 'Control+Alt+E'
    descId: 'shortcut008'
  upload_presentation: 
    keys: 'Control+Alt+Y'
    descId: 'shortcut009'
  open_shortcut: 
    keys: 'Control+Alt+H'
    descId: 'shortcut010'
