name: Typescript - validate code (eslint)
on:
  push:
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Fetch all history
      - name: run npm install
        working-directory: bigbluebutton-html5
        run: npm install
      - name: run ts
        working-directory: bigbluebutton-html5
        run: eslint . --ext .ts,.tsx